# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Civic Unrest
email: shelby@civicunrest.com
tagline: ""
description: >- # this means to ignore newlines until "baseurl:"
  A home for questions and research about civic technology.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://civicunrest.com"
canonical: "https://civicunrest.com"
twitter_username: civic_unrest

# Owner/author information
owner:
  name:           Shelby Switzer
  # avatar:         avatar.png
  # bio:            
  email:          shelby@civicunrest.com
  twitter:        switzerly
  github:         switzersc
  # disqus:         
  location:       "New York, NY"

# Build settings
markdown: kramdown
future:      true
highlighter: rouge



plugins:
  - jekyll-paginate

paginate: 10

timezone:    America/New_York	

sass:
  style: :compressed

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# Open Graph customization
opengraph:
  locale:           en_US
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
links:
  - title: About
    url: /about

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

permalink:   /:year/:month/:day/:title
